# .github/dependabot.yml
# Basic dependabot configuration for Python projects

version: 2
updates:
  - package-ecosystem: "pip" # Use the pip package manager for Python
    directory: "/" # Location of package manifests (requirements.txt)
    schedule:
      interval: "weekly" # Check for updates once a week
    allow:
      - dependency-type: "all"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  # Removed monitoring for /telegram_terminal_bot (not part of deploy scope)
    # You can add reviewers or assignees automatically if you want
    # assignees:
    #   - "amirbiron"
