# .github/dependabot.yml
# Basic dependabot configuration for Python projects

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"  # Dependabot does not support biweekly; use weekly
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "all"
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:15"
      timezone: "UTC"
    open-pull-requests-limit: 1
    groups:
      docker-dependencies:
        patterns:
          - "*"
  # Removed monitoring for /telegram_terminal_bot (not part of deploy scope)
    # You can add reviewers or assignees automatically if you want
    # assignees:
    #   - "amirbiron"
