version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip

environment:
  variables:
    DISABLE_DB: "true"
    SPHINX_MOCK_IMPORTS: "true"
    BOT_TOKEN: "dummy_bot_token_for_docs"
    MONGODB_URL: "mongodb://localhost:27017/test"