global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'code-keeper-bot'
    metrics_path: /metrics
    static_configs:
      - targets: ['code-keeper-bot:8000']
