name: "🔄 Biweekly Transitive Dependencies Bump"

on:
  schedule:
    # Every 1st and 15th of the month at 02:10 UTC
    - cron: '10 2 1,15 * *'
  workflow_dispatch:

jobs:
  bump-transitives:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install project (eager upgrade of transitive deps)
        run: |
          # Ensure constraints are respected while upgrading transitive deps
          # The "-U --upgrade-strategy eager" updates dependencies of dependencies
          python -m pip install -U --upgrade-strategy eager -r requirements.txt

      - name: Generate constraints.lock.txt (full transitive pin)
        run: |
          # Freeze the full environment to lock transitive deps
          python -m pip freeze --exclude-editable \
            | grep -Ev '^(pip|setuptools|wheel)==|^pkg-resources==0.0.0$' \
            > constraints.lock.txt
          echo "Created constraints.lock.txt:" && head -n 20 constraints.lock.txt || true

      - name: Ensure requirements.txt includes constraints.lock.txt
        shell: bash
        run: |
          set -euo pipefail
          if ! grep -qE '^\-c\s+constraints.lock.txt\s*$' requirements.txt; then
            # insert a new constraints line right after the existing constraints.txt line if present,
            # otherwise add at the top for precedence
            if grep -nE '^\-c\s+constraints.txt\s*$' requirements.txt >/dev/null; then
              line=$(grep -nE '^\-c\s+constraints.txt\s*$' requirements.txt | head -n1 | cut -d: -f1)
              awk -v ln="$line" 'NR==ln{print; print "-c constraints.lock.txt"; next}1' requirements.txt > req.tmp && mv req.tmp requirements.txt
            else
              { printf '%s\n' '-c constraints.lock.txt'; cat requirements.txt; } > req.tmp && mv req.tmp requirements.txt
            fi
            echo "Added '-c constraints.lock.txt' to requirements.txt"
          else
            echo "requirements.txt already references constraints.lock.txt"
          fi

      - name: Install test deps
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "deps: biweekly transitive upgrade (constraints.lock)"
          commit-message: |
            deps: biweekly transitive upgrade (constraints.lock)

            - Update transitive deps via pip --upgrade-strategy eager
            - Generate constraints.lock.txt to lock resolved versions
            - Ensure requirements.txt uses constraints.lock.txt
          body: |
            Automated biweekly update of transitive dependencies.
            - Uses eager upgrade to refresh indirect dependencies
            - Locks resolved versions in constraints.lock.txt
            - Runs tests to validate
          branch: chore/biweekly-transitive-bump
          base: ${{ github.ref_name || 'main' }}
          signoff: true
          labels: dependencies, security
          draft: false
