name: "📦 Monthly Dependency Update"

on:
  schedule:
    - cron: "0 2 1 * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/dependency-update-pr.yml"
      - "requirements.txt"
      - "requirements.prod.txt"
      - "webapp/requirements.txt"
      - "docs/requirements.txt"
      - "constraints.txt"

jobs:
  update-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: No-op bump (Dependabot handles updates)
        run: echo "No direct bumps. Triggering CI/Dependabot."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deps): monthly refresh (trigger CI)"
          title: "chore(deps): monthly dependency refresh"
          body: |
            Automated monthly dependency refresh.
            - Triggers CI and Dependabot checks
            - Please review updates and ensure tests pass
          branch: chore/monthly-deps-refresh
          delete-branch: true
          signoff: true
