name: "📦 Monthly Dependency Update"

on:
  schedule:
    - cron: "0 2 1 * *"  # Every month on the 1st at 02:00 UTC
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/dependency-update-pr.yml"
      - "requirements.txt"
      - "requirements.prod.txt"
      - "webapp/requirements.txt"
      - "docs/requirements.txt"
      - "constraints.txt"

jobs:
  update-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Bump requirements (best-effort)
        run: |
          set -e
          if [ -f requirements.txt ]; then
            # Try to update direct pins in requirements.txt conservatively
            python - << 'PY'
          import re
          path = 'requirements.txt'
          data = open(path, 'r', encoding='utf-8').read()
          def bump_pin(line: str) -> str:
              m = re.match(r"([^=<>!\s#]+)(==)([0-9a-zA-Z\.-]+)(.*)$", line)
              return line if not m else f"{m.group(1)}=={m.group(3)}{m.group(4)}\n"
          # This placeholder keeps versions; real upgrades are handled by Dependabot/PR review.
          open(path, 'w', encoding='utf-8').write(data)
          print('Kept pinned versions; rely on Dependabot for bumps.')
          PY
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deps): monthly refresh (trigger Dependabot and CI)"
          title: "chore(deps): monthly dependency refresh"
          body: |
            Automated monthly dependency refresh.

            - Triggers CI and Dependabot checks
            - Please review updates and ensure tests pass
          branch: chore/monthly-deps-refresh
          delete-branch: true
          signoff: true
