name: 📚 Build Documentation (Sphinx)

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

jobs:
  build-docs:
    name: Build Sphinx Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      - name: Build documentation
        env:
          DISABLE_DB: "true"
          SPHINX_MOCK_IMPORTS: "true"
          BOT_TOKEN: "dummy_bot_token_for_docs"
          MONGODB_URL: "mongodb://localhost:27017/test"
        run: |
          cd docs
          sphinx-build -b html . _build/html -W --keep-going

      - name: Upload docs artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

