name: Monthly Render Redeploy

on:
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -sS -X POST "$RENDER_DEPLOY_HOOK" || true
name: "♻️ Monthly Render Redeploy"

on:
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -sS -X POST "$RENDER_DEPLOY_HOOK" || true
